export const FRIEND_SELECTED ='FRIEND_SELECTED';
export const REGISTER = 'REGISTER';
export const REQUEST_NUMBER = 'REQUEST_NUMBER';
export const USERS_FRIENDS = 'USERS_FRIENDS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';